import type { Metadata } from "next";
import "./globals.css";
import { ReduxProvider } from "../store/provider";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import GlobalLoader from "@/components/GlobalLoader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ReduxProvider>
          <div className="flex flex-col min-h-screen">
            <Header />
            <GlobalLoader />
            <main className="flex-1">{children}</main>
            <Footer />
          </div>
        </ReduxProvider>
        ;
      </body>
    </html>
  );
}
